---
title: "lab1"
author: "Hyeonjin Cha"
date: "1/13/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("patchwork")
library(tidyverse)
library(here)
library(rio)
library(knitr)
library(janitor)
library(patchwork)
library(ggplot2)
library(forcats)
library(lubridate)

```

## load the dataset
```{r rstats}
rstats <- import(here("data", "rstats_tweets.rds")) %>% 
  clean_names() %>% 
  as_tibble()
view(rstats)
```

```{r plot1}
top25<-rstats %>%
  count(screen_name,sort=TRUE)

top25$screen_name <- factor(top25$screen_name) 
fct_reorder(top25$screen_name,top25$n, .desc=TRUE)

sample<-top25%>%
  slice_head(n=25)

ggplot(sample,aes(fct_reorder(screen_name,n),n)) +
  geom_col() +
  coord_flip()

```

```{r plot2}
#create month variable from created_at column and cout the row numbers
 
plot2  <- 
  rstats %>%  
    count(month = round_date(created_at,"month"))

#plot draft of plot 2
ggplot(plot2, aes(month, n)) +
  geom_line() +
  geom_smooth() +
  xlab("Year (data summarized by month") +
  ylab("Number of #rstats tweets") +
  labs(title = "Growth of the #rstats hashtag on twitter over time") +
  coord_cartesian(xlim = lubridate::as_datetime(c("2008-01-01","2018-12-01")), 
                  ylim = c(0,12000),
                  expand = F)


  
  
   
```
